adamghill/django-unicorn

- django_unicorn/components.py
- django_unicorn/message.py
- django_unicorn/static/js/component.js
- django_unicorn/static/js/element.js
- django_unicorn/static/js/messageSender.js
- django_unicorn/views.py
- example/unicorn/components/polling.py
- tests/js/element/poll.test.js
- tests/views/fake_components.py
- tests/views/message/test_call_method.py
It would be helpful to also be able to negate the disable modifier.
```html
<div unicorn:poll-1000="get_date" unicorn:poll.disable="!polling_enabled">
...
</div>
```
> Change polling options from an action method

- django_unicorn/static/js/attribute.js
- django_unicorn/static/js/component.js
- django_unicorn/static/js/element.js
- django_unicorn/static/js/eventListeners.js
- django_unicorn/static/js/messageSender.js
- django_unicorn/static/js/morphdom/2.6.1/options.js
- example/unicorn/templates/unicorn/text-inputs.html
- tests/js/component/models.test.js
- tests/js/element/dirty.test.js
- tests/js/element/loading.test.js
> Initial support for `unicorn:dirty`

- django_unicorn/components/unicorn_template_response.py
- django_unicorn/components/unicorn_view.py
- django_unicorn/static/js/component.js
- django_unicorn/static/js/messageSender.js
- django_unicorn/views.py
- example/unicorn/components/js.py
- example/unicorn/templates/unicorn/js.html
- tests/components/test_get_locations.py
- tests/templatetags/test_unicorn_render.py
- tests/views/message/test_calls.py
- tests/views/message/utils.py
For https://github.com/adamghill/django-unicorn/issues/138.
> Call JavaScript functions from the component view

- django_unicorn/static/js/morphdom/2.6.1/morphdom.js
- django_unicorn/static/js/unicorn.js
- example/unicorn/components/js.py
- example/unicorn/templates/unicorn/js.html
- tests/js/unicorn/call.test.js
- tests/js/unicorn/getComponent.test.js
- tests/js/utils/morphdom.test.js
Also adds support for `Unicorn.call` for arguments.
> `unicorn:ignore` attribute

- django_unicorn/static/js/component.js
- example/unicorn/components/js.py
- example/unicorn/templates/unicorn/js.html
- tests/js/component/callCalls.test.js
PR for https://github.com/adamghill/django-unicorn/issues/170.
> Call a function in a JavaScript module

- django_unicorn/static/js/component.js
- django_unicorn/static/js/element.js
- django_unicorn/static/js/eventListeners.js
- django_unicorn/views/__init__.py
- django_unicorn/views/objects.py
- example/unicorn/templates/unicorn/html-inputs.html
- tests/js/element/partial.test.js
> Target multiple partials

- django_unicorn/management/commands/startunicorn.py
- tests/management/commands/startunicorn/test_handle.py
Based off of https://github.com/adamghill/django-unicorn/pull/229.
> `startunicorn` app path

- django_unicorn/static/unicorn/js/component.js
- django_unicorn/static/unicorn/js/element.js
- django_unicorn/static/unicorn/js/eventListeners.js
- django_unicorn/static/unicorn/js/unicorn.js
- example/unicorn/templates/unicorn/objects.html
- pyproject.toml
- tests/js/element/action.test.js
For https://github.com/adamghill/django-unicorn/discussions/234.
> Action debounce

- django_unicorn/static/unicorn/js/component.js
- django_unicorn/static/unicorn/js/messageSender.js
- django_unicorn/static/unicorn/js/store.js
- django_unicorn/static/unicorn/js/unicorn.js
- example/unicorn/templates/unicorn/hello-world-test.html
- pyproject.toml
Add Unicorn lifecycle events that outside JavaScript can hook into. #251
> Lifecycle events

- conftest.py
- django_unicorn/components/unicorn_view.py
- django_unicorn/templatetags/unicorn.py
- example/unicorn/templates/unicorn/hello-world-test.html
- tests/templates/test_component_kwargs.html
- tests/templates/test_template.html
- tests/templatetags/test_unicorn_render.py
- tests/urls.py
Fixes https://github.com/adamghill/django-unicorn/issues/300.
> Keep request context in unicorn templates

- django_unicorn/serializer.py
- tests/components/test_component.py
- tests/serializer/test_dumps.py
Should solve some of https://github.com/adamghill/django-unicorn/issues/303.
> Optimize the database calls for serializing models with many-to-many fields

- django_unicorn/management/commands/startunicorn.py
For https://github.com/adamghill/django-unicorn/issues/299.
> Handle creating nested components from `startunicorn`

- django_unicorn/CHANGELOG.md
- django_unicorn/components/unicorn_view.py
- pyproject.toml
- tests/components/test_component.py
- tests/views/fake_components.py
This should fix a bug with forms and `BooleanField`s reported by @zurtri.
> Fix checkbox widgets

- django_unicorn/components/unicorn_view.py
- django_unicorn/errors.py
- tests/components/test_get_locations.py
- tests/views/message/test_message.py
For https://github.com/adamghill/django-unicorn/issues/373.
> Better error messages when a component cannot be loaded

- django_unicorn/views/__init__.py
- docs/source/actions.md
- docs/source/validation.md
- tests/views/fake_components.py
- tests/views/message/test_call_method.py
For https://github.com/adamghill/django-unicorn/issues/364.
> Handle `ValidationError` being raised from an action method

- docs/source/actions.md
> document bool arguments

- conftest.py
- django_unicorn/components/unicorn_template_response.py
- django_unicorn/settings.py
- docs/source/settings.md
- tests/templatetags/test_unicorn_render.py
- tests/test_settings.py
This should probably be configurable in case it causes any issues. For https://github.com/adamghill/django-unicorn/issues/386.
> Put script inside of the component instead of outside of it

- django_unicorn/components/unicorn_view.py
- django_unicorn/utils.py
> Handle `cachetools` imports moving in 5.0.0

- django_unicorn/components/unicorn_view.py
- example/apps/main/components/sidebar_menu.py
- tests/components/test_get_locations.py
> Handle installed app with `apps` in name, but isn't `AppConfig`

- django_unicorn/static/unicorn/js/eventListeners.js
> Added eventType existence check in eventListeners.addActionEventListener

- django_unicorn/components/unicorn_view.py
- django_unicorn/views/action_parsers/utils.py
- django_unicorn/views/utils.py
- tests/views/fake_components.py
- tests/views/message/test_set_property.py
Fixes https://github.com/adamghill/django-unicorn/issues/434.
> Make sure that `updated_` and `updating_` methods are only called once

- docs/source/index.md
- added more excitement to reflect how useful the project is
- give more context as to where unicorn fits into the django ecosystem
- moved advert to the bottom to make the project a little more serious
- Moved changelog and faq lower in nav to allow focus on introduction and installation
> [Docs] Improve introduction

- django_unicorn/static/unicorn/js/eventListeners.js
- django_unicorn/static/unicorn/js/utils.js
- docs/source/loading-states.md
- package-lock.json
- tests/js/element/action.test.js
- tests/js/utils/toRegExp.test.js
> Multiple action elements

- django_unicorn/static/unicorn/js/element.js
- example/unicorn/components/html_inputs.py
- example/unicorn/templates/unicorn/html-inputs.html
> Do not set null value for select elements because it clears the display

- django_unicorn/static/unicorn/js/messageSender.js
- django_unicorn/views/__init__.py
- tests/templates/test_component_parent_with_value.html
- tests/views/message/test_hash.py
- tests/views/message/utils.py
> Do not send a 304 if a component has a parent

- django_unicorn/views/__init__.py
- docs/source/troubleshooting.md
- example/unicorn/templates/unicorn/hello-world-test.html
Make sure that the CSRF cookie is written before hitting the POST endpoint. For #614
> Add `ensure_csrf_cookie` to POST endpoint

- django_unicorn/templatetags/unicorn.py
- django_unicorn/views/__init__.py
- example/www/templates/www/index.html
- tests/templatetags/test_unicorn_render.py
Fix for https://github.com/adamghill/django-unicorn/issues/630.
> Invalid component kwargs should be `None`

- CONTRIBUTING.md
- DEVELOPING.md
- django_unicorn/cacher.py
- django_unicorn/components/unicorn_view.py
- django_unicorn/management/commands/startunicorn.py
- django_unicorn/templatetags/unicorn.py
- django_unicorn/typer.py
- pyproject.toml
- tests/call_method_parser/test_parse_kwarg.py
- tests/components/test_get_locations.py
- tests/test_settings.py
- tests/views/fake_components.py
- tests/views/test_is_component_field_model_or_unicorn_field.py
For https://github.com/adamghill/django-unicorn/issues/698. @mihrab34 how does this look for an initial doc?
> Add contributing

- conftest.py
- django_unicorn/cacher.py
- django_unicorn/components/unicorn_template_response.py
- django_unicorn/components/unicorn_view.py
- django_unicorn/typer.py
- django_unicorn/utils.py
- docs/source/changelog.md
- docs/source/views.md
- poetry.lock
- tests/components/test_component.py
- tests/components/test_create.py
- tests/templatetags/test_unicorn_render.py
- tests/test_cacher.py
- tests/test_model_lifecycle.py
- tests/test_typer.py
- tests/test_utils.py
- tests/views/action_parsers/call_method/test_call_method_name.py
- tests/views/action_parsers/utils/test_set_property_value.py
- tests/views/message/test_message.py
- tests/views/test_is_component_field_model_or_unicorn_field.py
- tests/views/test_unicorn_dict.py
- tests/views/test_unicorn_field.py
- tests/views/test_unicorn_model.py
- tests/views/test_unicorn_set_property_value.py
- tests/views/test_unicorn_view_init.py
- tests/views/utils/test_set_property_from_data.py
This will allow components to be defined in Python code without requiring a separate HTML template file.
```python
from django_unicorn.components import UnicornView
class CounterView(UnicornView):
template_html = """<div>
<div>
Count: {{ count }}
</div>
<button unicorn:click="increment">+</button>
<button unicorn:click="decrement">-</button>
</div>
"""
count: int
def increment(self):
count += 1
def decrement(self):
count -= 1
```
> `UnicornView.template_html` for components

- django_unicorn/cacher.py
- django_unicorn/call_method_parser.py
- django_unicorn/components/unicorn_template_response.py
- django_unicorn/components/unicorn_view.py
- django_unicorn/management/commands/startunicorn.py
- django_unicorn/serializer.py
- django_unicorn/typer.py
- django_unicorn/utils.py
- django_unicorn/views/__init__.py
- django_unicorn/views/action_parsers/call_method.py
- django_unicorn/views/action_parsers/utils.py
- mypy.ini
- pyproject.toml
MyPy type checking to resolve issue https://github.com/adamghill/django-unicorn/issues/705
> Mypy type checking

- docs/source/conf.py
- docs/source/getting-started.md
- docs/source/index.md
- docs/source/installation.md
- poetry.lock
- pyproject.toml
I added a "Getting Started" section to better indicate that Python/Django are pre-requisites to using Django Unicorn, as well as adding a small note on the installation instructions about templates.
> Add "Getting Started" Section and update "Installation" section
