- .dj-config.toml
- .github/workflows/python.yml
- .gitignore
- conftest.py
- django_unicorn/components.py
- django_unicorn/message.py
- django_unicorn/settings.py
- django_unicorn/static/js/component.js
- django_unicorn/static/js/messageSender.js
- django_unicorn/views.py
- example/project/settings.py
- example/unicorn/components/polling.py
- example/unicorn/templates/unicorn/polling.html
- poetry.lock
- pyproject.toml
- pytest.ini
- tests/test_settings.py
- tests/views/message/test_call_method.py
- tests/views/message/test_call_method_multiple.py
- tests/views/message/test_db_input.py
- tests/views/message/test_message.py
- tests/views/message/test_set_property.py
- tests/views/message/test_sync_input.py
- tests/views/message/test_target.py
- tests/views/message/test_toggle.py
Not sure if this is a good idea or not and there are probably some edge cases to think through. Might even want a setting to enable this functionality.
Still missing is a way to merge the resulting data from the current request into the data stored in the next request that happened while the first was processing.
This PR is a potential solution for #117.
> Queue up requests by component id

- pyproject.toml
- tests/views/test_unicorn_dataclass.py
I had some problems with the latest release on python 3.6, related to the added support for dataclasses.
I'm not totally sure what the problems are, since it worked locally, most likely because the dataclasses backport is a dependency for pydantic (which is only a dev dependency).
So maybe it is ok to add dataclasses as a dependency for python 3.6? I also added a simple test for dataclasses, although I have never used them myself.
> dataclasses dependency for 3.6 and test

- django_unicorn/static/js/component.js
I'm using a large polling interval (~ 10 seconds) for some pages, where the user tends to move to another page, and then come back to check if there is a result.
If I understand the code correctly, moving away from the page will disable polling, and when focusing the page again it will always init the polling with the polling interval **before** calling the poll function and user then some times executes a manual refresh and sees that there is indeed a result.
Not sure if it applies to all use cases, but I propose to execute the call method immediately on focus.
The code in this PR solves this for my use case, but please give feedback if there are any concerns of problems this might cause.
> call poll method immediately on focus

- django_unicorn/static/unicorn/js/component.js
- django_unicorn/static/unicorn/js/utils.js
- example/unicorn/templates/unicorn/nested/table.html
- tests/js/utils.js
- tests/js/utils/walk.test.js
For #261, instead of breaking out of the walker use a [NodeFilter](https://developer.mozilla.org/en-US/docs/Web/API/NodeFilter) to reject the top element of a nested component (using same logic if element has got a `unicorn:checksum` attr). 
When used with a tree walker rejecting a node from the filter skips the current node plus any descendants. In context of the `refreshEventListeners` function it achieves the same thing as before by not traversing a nested component, but continues to walk any elements that might come after it.
> Use node filter to skip nested components when walking

- django_unicorn/static/unicorn/js/attribute.js
- django_unicorn/static/unicorn/js/component.js
- django_unicorn/static/unicorn/js/element.js
- example/unicorn/components/js.py
- example/unicorn/templates/unicorn/js.html
- tests/js/element/visibility.test.js
This implements a way to call a server-side method when an element becomes visible on a page. https://github.com/adamghill/django-unicorn/discussions/270
> Proof of concept for calling a method when an element becomes visible

- django_unicorn/components/unicorn_view.py
- tests/components/test_get_locations.py
Fixes #267 
I think this should fix the issue.
@adamghill - Do let me know if there is a better way to test an app in `INSTALLED_APPS` that doesn't actually exist.
> Use rindex when handling installed app that points to an app config

- conftest.py
- django_unicorn/components/unicorn_template_response.py
- django_unicorn/settings.py
- django_unicorn/views/__init__.py
- noxfile.py
- poetry.lock
- pyproject.toml
- tests/templatetags/test_unicorn_render.py
- tests/test_settings.py
Includes:
- condense the JSON returned in the AJAX response
- add optional compression of HTML in the AJAX response
More details about HTML compression:
I tried both [`minify-html`](https://github.com/wilsonzlin/minify-html) and [`html-min`](https://htmlmin.readthedocs.io/) libraries for compressing the HTML.
Even with the sanest config options I could find for `minify-html` the HTML would get rendered a little weird sometimes and (I think) morphdom would lose the ability to morph from the initial HTML to the newly returned HTML. I tried this:
```
minified_html = minify(
rendered_template,
do_not_minify_doctype=True,
ensure_spec_compliant_unquoted_attribute_values=True,
keep_closing_tags=True,
keep_html_and_head_opening_tags=True,
keep_spaces_between_attributes=True,
keep_comments=True, …
```
> Minify response

- django_unicorn/components/unicorn_template_response.py
- django_unicorn/views/__init__.py
- django_unicorn/views/objects.py
- tests/views/fake_components.py
- tests/views/message/test_call_method.py
- tests/views/message/test_call_method_multiple.py
- tests/views/message/test_set_property.py
- tests/views/message/test_target.py
- tests/views/message/test_toggle.py
- tests/views/message/utils.py
1. Fixes a bug where dictionary keys were sorted differently which would change the generated checksum.
2. Should remove some processing time on every render that was happening unnecessarily.
> Remove calling `orjson.dumps` before every data checksum

- .editorconfig
- django_unicorn/call_method_parser.py
- django_unicorn/views/action_parsers/call_method.py
- django_unicorn/views/objects.py
- example/unicorn/components/models.py
- example/unicorn/templates/unicorn/models.html
- tests/call_method_parser/test_parse_call_method_name.py
- tests/views/action_parsers/call_method/test_call_method_name.py
I was experiencing a problem with Unicorn, so here are some fixes.
Given: a component view method with single argument, type-hinted as a Model.
Problem: consecutive calls to the method with the same arguments would result in successful first call, but exceptions in next calls. Behavior repeats with restart of a worker.
It would seem that `parse_call_method_name()` output in the `lru_cache` would later be mutated, resulting in incorrect caching.
P.S. And a few other fixes - I noticed some small problems on the way.
> Fixes for argument mutations when calling view methods

- django_unicorn/components/unicorn_view.py
- django_unicorn/utils.py
- django_unicorn/views/__init__.py
- tests/test_utils.py
When caching, switch children and parents to dummy references. Switch back when un-caching. Simplify setting parent/child releationships.
> Caching with parent/children multiple levels

- django_unicorn/utils.py
This is an ABC that never really made much sense and was deprecated in https://github.com/python/cpython/issues/91896
> Remove use of collections.abc.ByteString

- django_unicorn/components/unicorn_view.py
I ran into a problem using AuthenticationForm as form_class in UnicornView due to the extra `request` argument in the forms constructor. This caused form data to be passed incorrectly in _get_form and was fixed by simply changing "data" to a keyword argument.
My component:
```python
from django_unicorn.components import UnicornView
from django.contrib.auth.forms import AuthenticationForm
class AuthenticateView(UnicornView):
form_class = AuthenticationForm
username = ""
password = ""
```
Cause the error:
```
'AuthenticationForm' object has no attribute 'cleaned_data'
```
While not necessarily condoning the use of authentication forms with unicorn, a temporary fix to a problem like this can be solved by inheriting the form class and changing `init`, like this:
```python
class …
```
> Pass "data" as a keyword argument when instantiating form_class

- docs/source/faq.md
Fix a spelling typo and some grammar issues in the "Do I need to install GraphQL to use Unicorn?" section of the FAQ.
> Fix spelling and grammar in FAQ

- django_unicorn/call_method_parser.py
- django_unicorn/components/unicorn_view.py
- django_unicorn/templatetags/unicorn.py
- docs/source/advanced.md
- tests/templates/test_component_args.html
- tests/templatetags/test_unicorn_render.py
Kwargs were able to be passed into components, but not arguments. This adds that capability and also exposes `component_args` and `component_kwargs` as instance methods on the component.
> Handle component arguments

- django_unicorn/call_method_parser.py
- django_unicorn/serializer.py
- django_unicorn/static/unicorn/js/messageSender.js
- django_unicorn/utils.py
- django_unicorn/views/__init__.py
- django_unicorn/views/action_parsers/call_method.py
- django_unicorn/views/objects.py
- example/unicorn/components/objects.py
- example/unicorn/templates/unicorn/objects.html
- tests/serializer/test_dumps.py
- tests/views/action_parsers/call_method/test_call_method_name.py
When type annotations are used in args or kwargs in a method used for an action, `Unicorn` will attempt to coerce the argument into the type annotation. Solves for https://github.com/adamghill/django-unicorn/issues/514.
```python
from django_unicorn.components import UnicornView
from datetime import datetime
class TestComponent(UnicornView):
def check_datetime(self, _datetime: datetime):
assert isinstance(_datetime) is datetime
```
```html
<div>
<button u:click='check_datetime("2020-09-12T01:01:01")'>check with a static string</button>
<button u:click='check_datetime("{{ date_example|date:'c' }}")'>check with a dynamic string</button>
<button u:click='check_datetime({{ date_example|date:'U' }})'>check with epoch (notice no quotes around the arg to check_datetime)</button>
</div>
```
> Use type hints in action args/kwargs

- django_unicorn/components/unicorn_template_response.py
This pull request extends the regex in `is_html_well_formed() ` to no longer raise a warning when the template html contains a custom tag.
Some icon libraries, namely ionicons which adds a custom html tag e.g.: ion-icon
> Note that custom element names [require a dash to be used in them](https://html.spec.whatwg.org/multipage/custom-elements.html#valid-custom-element-name) (kebab-case); they can't be single words.
[developer.mozilla.org](https://developer.mozilla.org/en-US/docs/Web/API/Web_components/Using_custom_elements#high-level_view)
> Allow custom html tags to be valid

- django_unicorn/call_method_parser.py
- django_unicorn/utils.py
- django_unicorn/views/action_parsers/call_method.py
- django_unicorn/views/utils.py
- example/unicorn/components/objects.py
- example/unicorn/components/test_datetime.py
- example/unicorn/templates/unicorn/objects.html
- example/unicorn/templates/unicorn/test-datetime.html
- example/www/templates/www/test-datetime.html
- tests/call_method_parser/test_parse_args.py
- tests/views/utils/test_set_property_from_data.py
This adds a page to the `example` folder that shows the issue of issue #514 persisting.
Checkout this branch, open `/test-datetime` and see the green button:
Click it, and the datetime turns into a str:
> add example for datetime props

- django_unicorn/views/__init__.py
This will make sure a component's parent request is set to the current request. Solves for https://github.com/adamghill/django-unicorn/issues/579.
> Set the component's parent request explicitly

- .github/workflows/python.yml
Assuming that we support Python 3.11, it is beneficial to run the tests for this version too.
> Run tests for Python 3.11 in GitHub Actions.

- django_unicorn/settings.py
When `MINIFY_HTML` is set to `True`, but `htmlmin` is not installed, 
the following warning is printed:
```
MINIFY_HTML is `True`, but minify extra could not be imported. Install with `unicorn[minify]`.
MINIFY_HTML is `True`, but minify extra could not be imported. Install with `unicorn[minify]`.
```
Users should be instructed to install `django-unicorn[minify] instead of `unicorn[minify]`
> Fixing erroneous installation instructions

- poetry.lock
- pyproject.toml
Since the project explicitly supports Python 3.8 and above, this should not be necessary.
> Remove dataclasses as a dependency for Python versions below 3.7.

- django_unicorn/typer.py
- tests/test_typer.py
For https://github.com/adamghill/django-unicorn/issues/639.
> Catch `NameError` when getting type hints

- django_unicorn/components/unicorn_view.py
- tests/components/test_get_locations.py
- tests/views/message/test_message.py
Add a fallback location for components for a defined place to look that doesn't require adding something to `INSTALLED_APPS`. Added for `Coltrane`, but this might be useful for other use-cases as well.
> Add fallback component location

- .github/workflows/python.yml
- django_unicorn/components/unicorn_template_response.py
- django_unicorn/components/unicorn_view.py
- django_unicorn/views/__init__.py
- docs/source/child-components.md
- docs/source/direct-view.md
- docs/source/views.md
- example/unicorn/templates/unicorn/nested/filter.html
- example/unicorn/templates/unicorn/nested/row.html
- pyproject.toml
- tests/components/test_unicorn_template_response.py
For #662 and CCing @jacksund for visibility.
Fixes a few issues:
- child components that had `force_render=True` would always get the parent component's outer element, however direct views are special since they are embedded in a regular template; make sure to send back the actual root element for the parent DOM
- clean up a logged warning about multiple elements for direct views
- clean up some docs
- fix the `'PointerUnicornView' object has no attribute 'component_id'` error that happens when refreshing a direct view
- more doc fixes to make `force_render` more clear
> Fix issues when using nested components in a direct view

- django_unicorn/management/commands/startunicorn.py
- django_unicorn/typer.py
- tests/serializer/test_dumps.py
- tests/test_typer.py
- tests/views/fake_components.py
Fixes #647 
Not super familiar with the codebase but this seems to work.
> Potential fix for #647

- django_unicorn/management/commands/startunicorn.py
- tests/management/commands/startunicorn/test_handle.py
- Preventing the `ask_for_star` message from spamming;
- Fixing the folder creation for nested components[1];
[1] I've noticed that creating two nested components in a row `python3 manage.py startunicorn app test_1.test_2.table test_3.test_4.row` goes wrong beacuse of `component_base_path` variable.
I also needed to add the creation os `app/templates/unicorn` to test file.
Hope it helps! :)
> [startunicorn] Extract methods from loop

- django_unicorn/components/unicorn_view.py
- django_unicorn/views/action_parsers/sync_input.py
- django_unicorn/views/action_parsers/utils.py
- docs/source/changelog.md
- docs/source/views.md
- tests/views/fake_components.py
- tests/views/message/test_set_property.py
This is a prototype to solve for https://github.com/adamghill/django-unicorn/discussions/696. It changes the semantics of how the updated methods work, though -- instead of getting called for every action, when there are multiple actions in a queue (for example with deferred), the updated method would only get called once for the last action.
I do wonder:
1.  If adding a new method (instead of using "updated") would be more appropriate, although I can't think of a good name for it.
2. Could I pass another argument along with the property value which indicates it's the last value in a queue? I can't think of a nice argument name for that either. Something like this arg name feels very messy, but would be "correct": `def updated_search(self, search, is_last_or_only_action`.
3. Another …
> When there are multiple actions in the queue, only call the "updated" methods for the last action

- .github/workflows/python.yml
- DEVELOPING.md
- noxfile.py
- poetry.lock
- pyproject.toml
- tests/serializer/test_dumps.py
- timezone information is now on by default, and serilizers are expecting zulu time.
- Replace manual timestamp truncation with datetime timespec set to milliseconds
> Add Django 5.0 to test matrix (fixes #704)

- README.md
- Just starting up with unicorn recently, great project. I think the `form_class` actually is missing from the README here. Let me know if that is not right.
> Fixed missing form_class in readme
